# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TinyMLaaS5',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/TinyMLaaS5',
                'lib_path': 'TinyMLaaS5'},
  'syms': {'TinyMLaaS5.core': {'TinyMLaaS5.core.foo': ('core.html#foo', 'TinyMLaaS5/core.py')}}}
